# SPDX-License-Identifier: GPL-3.0-only
"""Compile vendored Spleen 2.2.0 and original pixel icons to DOS C tables.

Generated fonts live in a separate immutable segment, outside the near heap.
Icons use three transparent masks: outline, body and highlight.
"""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]

# Convert BDF Unicode glyphs into a 256-entry CP437 table. Each scanline is
# one byte, high bit at the left, even for fonts narrower than eight pixels.
def font(size):
    text = (root / 'assets/fonts' / f'spleen-{size}.bdf').read_text()
    width, height = map(int,size.split('x'))
    glyphs = {}
    for glyph in re.findall(r'STARTCHAR .*?\n(.*?)ENDCHAR',text,re.S):
        encoding = int(re.search(r'^ENCODING (\d+)',glyph,re.M)[1])
        rows = [int(s,16) for s in glyph.split('BITMAP\n')[1].strip().splitlines()]
        assert len(rows) == height
        glyphs[encoding] = rows
    # Use light box drawing only when the requested double-line glyph is absent.
    fallback = {0x2550:0x2500,0x2551:0x2502,0x2554:0x250c,0x2557:0x2510,
                0x255a:0x2514,0x255d:0x2518,0x2560:0x251c,0x2563:0x2524,
                0x2566:0x252c,0x2569:0x2534,0x256c:0x253c}
    result = []
    for code in range(256):
        unicode = ord(bytes([code]).decode('cp437'))
        result += glyphs.get(unicode,glyphs.get(fallback.get(unicode),glyphs[63]))
    return result

# Emit immutable C byte tables; icons stay near, while font bytes use FONTDATA.
def table(name,data,far=False):
    rows=['    '+', '.join(f'0x{n:02x}' for n in data[i:i+16])+',' for i in range(0,len(data),16)]
    return f'static const unsigned char {"far " if far else ""}{name}[{len(data)}] = {{\n'+ '\n'.join(rows)+'\n};\n'

# X: outline, o: body, +: highlight, .: transparent. Aligned at 16 pixels.
icon_order = ('folder','parent','document','binary','program','archive','image','drive')
icons = {name: (root/'assets/icons'/f'{name}.txt').read_text().splitlines() for name in icon_order}

result='/* SPDX-License-Identifier: GPL-3.0-only */\n/* Generated by tools/assets.py; edit the generator or assets, not this file. */\n/* Icons: three consecutive masks (outline, body, highlight), two bytes per\n * row, most significant bit at the left. Unset pixels remain transparent.\n * Full/compact/CGA tables have 16/12/8 rows; compact rows pad to 16 bits.\n */\n#ifndef ASSETS_H\n#define ASSETS_H\n'
assembly = ["; SPDX-License-Identifier: GPL-3.0-only AND BSD-2-Clause",
            "; Spleen font data: BSD-2-Clause; see assets/FONT-LICENSE.txt.", ".8086", "; Generated by tools/assets.py; edit the generator, not this file.",
            "; CP437 glyphs: 256 characters, height bytes each, high bit at left.",
            "; Immutable fonts live outside DGROUP to preserve the near heap.",
            "FONTDATA segment para public 'CODE'"]
for size in ('5x8','6x12','8x16'):
    data = font(size)
    assembly.append('font_' + size.replace('x','_') + ' label byte')
    for i in range(0,len(data),16):
        assembly.append('    db ' + ','.join(f'0{n:02x}h' for n in data[i:i+16]))
# Help joins the fonts outside DGROUP. Fixed-width authored lines fit every
# viewport; heading markers affect color only, never font weight.
help_lines = (root/'assets/help.txt').read_text(encoding='ascii').splitlines()
assert help_lines and all(len(line) <= 66 for line in help_lines), 'Help lines must fit 66 columns'
assembly.append('help_offsets label word')
for i in range(len(help_lines)):
    assembly.append(f'    dw offset help_{i}')
for i, line in enumerate(help_lines):
    assembly.append(f'help_{i} label byte')
    data = line.encode('ascii') + b'\0'
    for at in range(0, len(data), 16):
        assembly.append('    db ' + ','.join(f'0{n:02x}h' for n in data[at:at+16]))
help_source = (
    '/* SPDX-License-Identifier: GPL-3.0-only */\n'
    '/* Generated by tools/assets.py from assets/help.txt. */\n'
    '#ifndef HELP_H\n#define HELP_H\n#include "NW.H"\n'
    f'#define HELP_LINES {len(help_lines)}\n#define HELP_WIDTH 66\n'
    'const char NW_FAR *asset_help(unsigned index);\n'
    'void help_line(unsigned index, char *out);\n#endif\n')
help_path = root/'src/HELP.H'
if not help_path.exists() or help_path.read_text() != help_source:
    help_path.write_text(help_source)
# The small-model C ABI returns a far pointer as DX:AX and passes mode at BP+4.
# All fonts share FONTDATA, so only the offset changes; mode 1/2 selects CGA/EGA,
# and the remaining path selects VGA. Keep the generated explanation with it.
assembly += ["FONTDATA ends", "_TEXT segment byte public 'CODE'", "assume cs:_TEXT",
             "; C small-model near call: mode at [BP+4], far result in DX:AX.",
             "; Modes 1/2 select 5x8/6x12; otherwise use 8x16. BP is preserved.",
             "public _asset_font", "_asset_font proc near", "push bp", "mov bp,sp",
             "mov dx,seg font_5_8", "mov ax,offset font_5_8", "cmp word ptr [bp+4],1",
             "je font_done", "mov ax,offset font_6_12", "cmp word ptr [bp+4],2",
             "je font_done", "mov ax,offset font_8_16", "font_done:", "pop bp", "ret",
             "_asset_font endp",
             "; Help index at BP+4; preserve DS/BX and return FONTDATA pointer in DX:AX.",
             "assume ds:FONTDATA", "public _asset_help", "_asset_help proc near", "push bp", "mov bp,sp",
             "push bx", "push ds", "mov ax,seg help_offsets", "mov ds,ax",
             "mov bx,[bp+4]", "shl bx,1", "mov ax,help_offsets[bx]", "mov dx,ds",
             "pop ds", "pop bx", "pop bp", "ret", "_asset_help endp", "_TEXT ends", "end"]
font_source = '\n'.join(assembly)+'\n'
font_path = root/'src/FONT.ASM'
if not font_path.exists() or font_path.read_text() != font_source: font_path.write_text(font_source)
for index,(name,rows) in enumerate(icons.items()):
    assert len(rows)==16 and all(len(row)==16 for row in rows),(name,rows)
    masks=[]
    for channel in 'Xo+':
        for row in rows:
            bits=int(''.join('1' if c==channel else '0' for c in row),2)
            masks.extend([bits>>8,bits&255])
    result+=f'#define ICON_{name.upper()} {index}\n'+table('icon_'+name,masks)
result+='static const unsigned char *icon_masks[] = { '+', '.join('icon_'+n for n in icons)+' };\n'
for name in icon_order:
    rows = (root/'assets/icons/compact'/f'{name}.txt').read_text().splitlines()
    assert len(rows) == 12 and all(len(row) == 12 for row in rows), name
    masks = []
    for channel in 'Xo+':
        for row in rows:
            bits = int(''.join('1' if c == channel else '0' for c in row) + '0000', 2)
            masks.extend([bits >> 8, bits & 255])
    result += table('compact_' + name, masks)
result += 'static const unsigned char *compact_icon_masks[] = { ' + ', '.join('compact_'+n for n in icons) + ' };\n#endif\n'
# CGA halves the 16-row icon vertically. Merge each pair of rows, then remove
# outline/body overlaps in priority order so three masks remain disjoint.
for name, rows in icons.items():
    masks = []
    for channel in range(3):
        for y in range(0, 16, 2):
            merged = []
            for c in 'Xo+':
                merged.append(int(''.join('1' if rows[y][x] == c or rows[y+1][x] == c else '0' for x in range(16)), 2))
            bits = merged[channel]
            if channel: bits &= ~merged[0]
            if channel == 2: bits &= ~merged[1]
            masks.extend([bits >> 8, bits & 255])
    result += table('cga_' + name, masks)
result = result.replace('#endif\n', '')
result += 'static const unsigned char *cga_icon_masks[] = { ' + ', '.join('cga_'+n for n in icons) + ' };\n#endif\n'
icon_path = root/'src/ASSETS.H'
if not icon_path.exists() or icon_path.read_text() != result: icon_path.write_text(result)
print('Generated CP437 fonts,',len(icons),'layered icons and',len(help_lines),'Help lines')
