# SPDX-License-Identifier: GPL-3.0-only
"""Generate build provenance without committing a stale Git revision."""
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def revision(root=ROOT):
    try:
        commit = subprocess.check_output(
            ['git', 'rev-parse', '--short=7', 'HEAD'], cwd=root,
            stderr=subprocess.DEVNULL, text=True).strip()
        if subprocess.check_output(
                ['git', 'status', '--porcelain'],
                cwd=root, stderr=subprocess.DEVNULL, text=True).strip():
            commit += '-dirty'
        return commit
    except (OSError, subprocess.CalledProcessError):
        return 'unknown'


def write(root=ROOT):
    target = root / 'src/BUILD.H'
    content = ('/* SPDX-License-Identifier: GPL-3.0-only */\n'
               '/* Generated by tools/build_metadata.py; do not edit. */\n'
               '#ifndef BUILD_H\n#define BUILD_H\n'
               f'#define NW_BUILD_COMMIT "{revision(root)}"\n'
               '#define NW_REPOSITORY "github.com/ifilot/nightwatch"\n'
               '#endif\n')
    if not target.exists() or target.read_text() != content:
        target.write_text(content, encoding='ascii')


if __name__ == '__main__':
    write()
