# SPDX-License-Identifier: GPL-3.0-only
"""Place zlib's immutable fixed Huffman tables outside DOS near data."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
text = (root/'vendor/zlib/inffixed.h').read_text()
lines = ['; zlib license: see vendor/zlib/LICENSE; generated by tools/zlib_tables.py',
         '.8086', "ZIPTABLE segment para public 'CODE'"]
for name, count in [('lenfix',512), ('distfix',32)]:
    body = re.search(r'code '+name+r'\[\d+\] = \{(.*?)\};',text,re.S)[1]
    values = [tuple(map(int,m)) for m in re.findall(r'\{(\d+),(\d+),(\d+)\}',body)]
    assert len(values)==count
    lines.append(name+' label byte')
    for op,bits,val in values:
        lines += [f'    db {op},{bits}',f'    dw {val}']
lines += ['ZIPTABLE ends', "FIXED_TEXT segment byte public 'CODE'", 'assume cs:FIXED_TEXT']
for name in ('lenfix','distfix'):
    lines += ['public _fixed_'+name, '_fixed_'+name+' proc far',
              'mov dx,seg '+name, 'mov ax,offset '+name, 'ret', '_fixed_'+name+' endp']
lines += ['FIXED_TEXT ends','end']
(root/'src/FIXED.ASM').write_text('\n'.join(lines)+'\n')
